# Basic options
title: Intro to Python
short_name: python-intro
developers: [Simon Kirby, Omar Jamil]
description: Learn the basics of one of the most popular programming languages around!
n_sessions: 2
prereq: No prerequesite knowledge required. Course attendees will have followed the installation process for Python and JupyterLab.
url: https://uniexeterrse.github.io/intro-to-python

markdown: kramdown

# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:path/index.html
    sort_by: lesson

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page

# Build settings
theme: jekyll-theme-slate
